[theme]
# Primary accent color for interactive elements.
primaryColor = "#009999"

# Background color for the main content area.
backgroundColor = "#F1F7FD"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#D4F0EC"

# Color used for almost all text.
textColor = "#003366"